Algoritmo "exerc_terreno"

Var

  largura, comprimento, metro2, area, preco : real

Inicio

  escreva("Digite a largura do terreno: ")
  leia(largura)
  escreva("Digite o comprimento do terreno: ")
  leia(Comprimento)
  escreva("Digite o valor do metro quadrado: ")
  leia(metro2)
  area <- comprimento * largura
  escreval("Area do terreno = ", area:8:2)
  preco <- area * metro2
  escreva("Preco do terreno = ", preco:8:2)

Fimalgoritmo